# Generated by Django 5.0.7 on 2024-07-15 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='crated_at',
            new_name='created_at',
        ),
    ]
